LOCATIONS = [
    ("New York", "NY"),
    ("Los Angeles", "CA"),
    ("Chicago", "IL"),
    ("Houston", "TX"),
    ("Phoenix", "AZ"),
    ("Philadelphia", "PA"),
    ("San Antonio", "TX"),
    ("San Diego", "CA"),
    ("Dallas", "TX"),
    ("San Jose", "CA"),
    ("Austin", "TX"),
    ("Jacksonville", "FL"),
    ("Fort Worth", "TX"),
    ("Columbus", "OH"),
    ("Charlotte", "NC"),
    ("San Francisco", "CA"),
    ("Indianapolis", "IN"),
    ("Seattle", "WA"),
    ("Denver", "CO"),
    ("Washington", "DC"),
    ("Boston", "MA"),
    ("El Paso", "TX"),
    ("Nashville", "TN"),
    ("Detroit", "MI"),
    ("Portland", "OR"),
    ("Memphis", "TN"),
    ("Oklahoma City", "OK"),
    ("Las Vegas", "NV"),
    ("Louisville", "KY"),
    ("Baltimore", "MD"),
    ("Milwaukee", "WI"),
    ("Albuquerque", "NM"),
    ("Tucson", "AZ"),
    ("Fresno", "CA"),
    ("Sacramento", "CA"),
    ("Kansas City", "MO"),
    ("Atlanta", "GA"),
    ("Miami", "FL"),
    ("Raleigh", "NC"),
    ("Omaha", "NE"),
    ("Colorado Springs", "CO"),
    ("Virginia Beach", "VA"),
    ("Long Beach", "CA"),
    ("Oakland", "CA"),
    ("Minneapolis", "MN"),
    ("Tampa", "FL"),
    ("Tulsa", "OK"),
    ("Arlington", "TX"),
    ("New Orleans", "LA"),
    ("Wichita", "KS"),
    ("Cleveland", "OH"),
    ("Bakersfield", "CA"),
    ("Aurora", "CO"),
    ("Anaheim", "CA"),
    ("Honolulu", "HI"),
    ("Santa Ana", "CA"),
    ("Riverside", "CA"),
    ("Corpus Christi", "TX"),
    ("Lexington", "KY"),
    ("St. Louis", "MO"),
    ("Pittsburgh", "PA"),
    ("Stockton", "CA"),
    ("Anchorage", "AK"),
    ("Cincinnati", "OH"),
    ("Saint Paul", "MN"),
    ("Toledo", "OH"),
    ("Greensboro", "NC"),
    ("Newark", "NJ"),
    ("Plano", "TX"),
    ("Henderson", "NV"),
    ("Lincoln", "NE"),
    ("Buffalo", "NY"),
    ("Fort Wayne", "IN"),
    ("Jersey City", "NJ"),
    ("Chula Vista", "CA"),
    ("Orlando", "FL"),
    ("St. Petersburg", "FL"),
    ("Norfolk", "VA"),
    ("Chandler", "AZ"),
    ("Laredo", "TX"),
    ("Madison", "WI"),
    ("Durham", "NC"),
    ("Lubbock", "TX"),
    ("Winston-Salem", "NC"),
    ("Garland", "TX"),
    ("Glendale", "AZ"),
    ("Hialeah", "FL"),
    ("Reno", "NV"),
    ("Baton Rouge", "LA"),
    ("Irvine", "CA"),
    ("Chesapeake", "VA"),
    ("Irving", "TX"),
    ("Scottsdale", "AZ"),
    ("North Las Vegas", "NV"),
    ("Fremont", "CA"),
    ("Gilbert", "AZ"),
    ("San Bernardino", "CA"),
    ("Boise", "ID"),
    ("Birmingham", "AL"),
]
