PERSONA_CLUSTERS = {
    "teen_student": {
        "age": (13, 19),
        "education": ["school"],
        "income": (0, 2000),
        "lifestyle": [
            "teen",
            "gaming",
            "social media",
            "sports",
            "music",
            "movies",
            "homework",
            "hanging out with friends",
            "dating",
            "part-time job",
            "driving lessons",
            "school clubs",
            "prom",
            "video streaming",
        ],
        "jobs": [
            "babysitter",
            "fast food worker",
            "lawn mowing",
            "pet sitting",
            "tutor",
            "camp counselor",
            "cashier",
            "lifeguard",
            "newspaper delivery",
            "retail associate",
            "ice cream scooper",
        ],
    },
    "poor_worker": {
        "age": (25, 60),
        "education": ["high_school"],
        "income": (15000, 30000),
        "lifestyle": [
            "budgeting",
            "overtime",
            "public transport",
            "second job",
            "living paycheck to paycheck",
            "DIY repairs",
            "food stamps",
            "shared housing",
            "discount stores",
            "night shifts",
            "physical labor",
            "minimal leisure",
            "health issues",
        ],
        "jobs": [
            "warehouse worker",
            "cleaner",
            "driver",
            "construction laborer",
            "factory worker",
            "security guard",
            "fast food cook",
            "cashier",
            "landscaper",
            "janitor",
            "delivery driver",
            "housekeeper",
            "waiter",
            "farmhand",
        ],
    },
"young_professional": {
    "age": (22, 35),
    "education": ["bachelor", "master"],
    "income": (40000, 90000),
    "lifestyle": [
        "career-focused",
        "fitness",
        "networking",
        "travel",
        "urban living",
        "startup culture",
        "coffee shops",
        "side projects",
        "craft beer",
        "brunch",
        "hiking",
        "tech gadgets",
        "concerts",
        "dating apps",
        "renting apartment",
        "student loan payments",
    ],
    "jobs": [
        "engineer",
        "designer",
        "analyst",
        "software developer",
        "consultant",
        "project manager",
        "marketing specialist",
        "data scientist",
        "financial analyst",
        "architect",
        "lawyer",
        "doctor",
        "pharmacist",
        "product manager",
        "UX/UI designer",
        "business analyst",
    ],
},
    "middle_class_parent": {
        "age": (30, 50),
        "education": ["bachelor"],
        "income": (45000, 80000),
        "lifestyle": [
            "parenting",
            "school runs",
            "weekend family time",
            "homeowner",
            "vacation planning",
            "PTA",
            "kid's activities",
            "soccer parent",
            "minivan",
            "backyard barbecues",
            "home improvement",
            "saving for college",
            "family vacations",
            "church",
            "neighborhood watch",
        ],
        "jobs": [
            "teacher",
            "manager",
            "accountant",
            "nurse",
            "social worker",
            "real estate agent",
            "small business owner",
            "administrative assistant",
            "sales representative",
            "HR specialist",
            "IT support",
            "police officer",
            "firefighter",
            "electrician",
            "plumber",
        ],
    },
    "retired": {
        "age": (60, 85),
        "education": ["high_school", "bachelor"],
        "income": (12000, 40000),
        "lifestyle": [
            "gardening",
            "grandparenting",
            "travel",
            "volunteering",
            "hobbies",
            "senior center",
            "fitness classes",
            "reading",
            "bingo",
            "cruises",
            "bird watching",
            "fishing",
            "cooking",
            "watching TV",
            "napping",
            "medicare",
        ],
        "jobs": [
            "retired",
            "part-time work",
            "volunteer",
            "consultant (retired)",
            "hobby farmer",
            "substitute teacher",
            "museum docent",
            "church volunteer",
            "greeter at store",
        ],
    },
    "college_student": {
        "age": (18, 25),
        "education": ["high_school", "some_college", "bachelor"],
        "income": (5000, 15000),
        "lifestyle": [
            "student",
            "party",
            "studying",
            "campus life",
            "dorm living",
            "extracurriculars",
            "internships",
            "exam stress",
            "student debt",
            "ramen diet",
            "all-nighters",
            "group projects",
            "sports clubs",
            "Greek life",
            "study abroad",
        ],
        "jobs": [
            "part-time",
            "intern",
            "tutor",
            "barista",
            "library assistant",
            "research assistant",
            "retail",
            "food delivery",
            "freelance",
            "campus tour guide",
            "teaching assistant",
            "resident advisor",
            "waiter",
            "call center agent",
        ],
    },
    "unemployed": {
        "age": (20, 60),
        "education": ["high_school", "some_college", "bachelor"],
        "income": (0, 10000),
        "lifestyle": [
            "struggling",
            "job-seeking",
            "job applications",
            "interviews",
            "training programs",
            "side hustles",
            "government assistance",
            "food banks",
            "budgeting",
            "anxiety",
            "skill development",
            "freelance gigs",
            "networking events",
            "online courses",
        ],
        "jobs": [
            "unemployed",
            "freelance",
            "gig worker",
            "daily labor",
            "temporary agency worker",
            "uber driver",
            "delivery person",
            "task rabbit",
            "pet sitting",
            "mowing lawns",
            "selling items online",
        ],
    },
}
